all:
	gcc -Wall -std=c99 -pedantic -g -o chess3 chess3.c
debug:
	gcc -Wall -DDEBUG -std=c99 -pedantic -g -o chess3 chess3.c
eat:
	gcc -Wall -DEAT -std=c99 -pedantic -g -o chess3 chess3.c
debugEat:
	gcc -Wall -DDEBUG -DEAT -std=c99 -pedantic -g -o chess3 chess3.c